networks:
  ciscoasa_local: null
services:
  ciscoasa:
    build: .
    container_name: ciscoasa
    restart: always
    tmpfs:
    - /tmp/ciscoasa:uid=2000,gid=2000
    networks:
    - ciscoasa_local
    ports:
    - ${CISCOASA_PORT1_SRC}:${CISCOASA_PORT1_DST}
    - ${CISCOASA_PORT2_SRC}:${CISCOASA_PORT2_DST}
    image: dtagdevsec/ciscoasa:24.04
    read_only: true
    volumes:
    - ${CISCOASA_VOL1_SRC}:${CISCOASA_VOL1_DST}
