networks:
  adbhoney_local: null
services:
  adbhoney:
    build: .
    container_name: adbhoney
    restart: always
    networks:
    - adbhoney_local
    ports:
    - ${ADBHONEY_PORT1_SRC}:${ADBHONEY_PORT1_DST}
    image: dtagdevsec/adbhoney:24.04
    read_only: true
    volumes:
    - ${ADBHONEY_VOL1_SRC}:${ADBHONEY_VOL1_DST}
    - ${ADBHONEY_VOL2_SRC}:${ADBHONEY_VOL2_DST}
