networks:
  cowrie_local: null
services:
  cowrie:
    build: .
    container_name: cowrie
    restart: always
    tmpfs:
    - /tmp/cowrie:uid=2000,gid=2000
    - /tmp/cowrie/data:uid=2000,gid=2000
    networks:
    - cowrie_local
    ports:
    - ${COWRIE_PORT1_SRC}:${COWRIE_PORT1_DST}
    - ${COWRIE_PORT2_SRC}:${COWRIE_PORT2_DST}
    image: ghcr.io/telekom-security/cowrie:24.04.1
    read_only: true
    volumes:
    - ${COWRIE_VOL1_SRC}:${COWRIE_VOL1_DST}
